[workspace]
resolver = "3"
members = [ "importer","src-tauri", "sum-tree", "xtask"]

[workspace.dependencies]
arrayvec = "0.7.6"
ctor = "0.5.0"
rand = "0.9.2"
rayon = "1.11.0"
tracing = "0.1.41"
chrono = { version = "0.4.39", default-features = true, features = ["serde"] }
thiserror = "1.0.69"
