[package]
name = "sum-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec.workspace = true
rand.workspace = true
rayon.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber = "0.3"
ctor.workspace = true
